services:
  frontend:
    build: .
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    environment:
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://backend:8000/api
